"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.StackAxis = void 0;
var StackAxis;
(function (StackAxis) {
    StackAxis[StackAxis["UP"] = 0] = "UP";
    StackAxis[StackAxis["DOWN"] = 1] = "DOWN";
    StackAxis[StackAxis["FORWARD"] = 2] = "FORWARD";
    StackAxis[StackAxis["BACKWARD"] = 3] = "BACKWARD";
    StackAxis[StackAxis["ALONG"] = 4] = "ALONG";
    StackAxis[StackAxis["AGAINST"] = 5] = "AGAINST";
})(StackAxis = exports.StackAxis || (exports.StackAxis = {}));
