"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.VoxChunk = void 0;
var flatbuffers = require("flatbuffers");
var VoxChunk = /** @class */ (function () {
    function VoxChunk() {
        this.bb = null;
        this.bb_pos = 0;
    }
    VoxChunk.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    VoxChunk.getRootAsVoxChunk = function (bb, obj) {
        return (obj || new VoxChunk()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    VoxChunk.getSizePrefixedRootAsVoxChunk = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new VoxChunk()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    VoxChunk.prototype.sizeX = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
    };
    VoxChunk.prototype.sizeY = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
    };
    VoxChunk.prototype.sizeZ = function () {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
    };
    VoxChunk.prototype.bitsPerIndex = function () {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
    };
    VoxChunk.prototype.palette = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    };
    VoxChunk.prototype.paletteLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    VoxChunk.prototype.paletteArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    VoxChunk.prototype.indices = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    };
    VoxChunk.prototype.indicesLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    VoxChunk.prototype.indicesArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    VoxChunk.startVoxChunk = function (builder) {
        builder.startObject(6);
    };
    VoxChunk.addSizeX = function (builder, sizeX) {
        builder.addFieldInt8(0, sizeX, 0);
    };
    VoxChunk.addSizeY = function (builder, sizeY) {
        builder.addFieldInt8(1, sizeY, 0);
    };
    VoxChunk.addSizeZ = function (builder, sizeZ) {
        builder.addFieldInt8(2, sizeZ, 0);
    };
    VoxChunk.addBitsPerIndex = function (builder, bitsPerIndex) {
        builder.addFieldInt8(3, bitsPerIndex, 0);
    };
    VoxChunk.addPalette = function (builder, paletteOffset) {
        builder.addFieldOffset(4, paletteOffset, 0);
    };
    VoxChunk.createPaletteVector = function (builder, data) {
        builder.startVector(1, data.length, 1);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    };
    VoxChunk.startPaletteVector = function (builder, numElems) {
        builder.startVector(1, numElems, 1);
    };
    VoxChunk.addIndices = function (builder, indicesOffset) {
        builder.addFieldOffset(5, indicesOffset, 0);
    };
    VoxChunk.createIndicesVector = function (builder, data) {
        builder.startVector(1, data.length, 1);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    };
    VoxChunk.startIndicesVector = function (builder, numElems) {
        builder.startVector(1, numElems, 1);
    };
    VoxChunk.endVoxChunk = function (builder) {
        var offset = builder.endObject();
        builder.requiredField(offset, 12); // palette
        builder.requiredField(offset, 14); // indices
        return offset;
    };
    VoxChunk.createVoxChunk = function (builder, sizeX, sizeY, sizeZ, bitsPerIndex, paletteOffset, indicesOffset) {
        VoxChunk.startVoxChunk(builder);
        VoxChunk.addSizeX(builder, sizeX);
        VoxChunk.addSizeY(builder, sizeY);
        VoxChunk.addSizeZ(builder, sizeZ);
        VoxChunk.addBitsPerIndex(builder, bitsPerIndex);
        VoxChunk.addPalette(builder, paletteOffset);
        VoxChunk.addIndices(builder, indicesOffset);
        return VoxChunk.endVoxChunk(builder);
    };
    return VoxChunk;
}());
exports.VoxChunk = VoxChunk;
