import defaultAvatar from "!!url-loader!../assets/models/DefaultAvatar.glb";

const names = [
  "Fluffy-Panda",
  "Snuggly-Bear",
  "Silly-Tiger",
  "Happy-Elephant",
  "Cheeky-Monkey",
  "Jolly-Giraffe",
  "Frisky-Cat",
  "Mischievous-Otter",
  "Playful-Dog",
  "Lively-Fox",
  "Cheery-Zebra",
  "Busy-Bee",
  "Pensive-Koala",
  "Dreamy-Deer",
  "Soft-Bunny",
  "Curly-Pig",
  "Flirty-Squirrel",
  "Adventurous-Bear",
  "Witty-Wolf",
  "Curious-Giraffe",
  "Jolly-Dog",
  "Cuddly-Cat",
  "Chirpy-Bird",
  "Furry-Lion",
  "Busy-Bee",
  "Plucky-Penguin",
  "Snazzy-Skunk",
  "Silly-Elephant",
  "Mischievous-Monkey",
  "Lively-Tiger",
  "Happy-Hippo",
  "Sleepy-Sloth",
  "Playful-Otter",
  "Cute-Kitten",
  "Jolly-Rabbit",
  "Cheery-Chimpanzee",
  "Frisky-Fox",
  "Lazy-Bear",
  "Busy-Bird",
  "Curious-Cat",
  "Lively-Giraffe",
  "Bouncy-Dog",
  "Grinning-Gorilla",
  "Playful-Pig",
  "Silly-Squirrel",
  "Happy-Hare",
  "Giggly-Llama",
  "Clever-Cat",
  "Snazzy-Skunk",
  "Jolly-Orangutan",
  "Bouncy-Kitten",
  "Happy-Hippo",
  "Fluffy-Bunny",
  "Lazy-Leopard",
  "Chirpy-Chipmunk",
  "Playful-Puppy",
  "Cuddly-Cub",
  "Snuggly-Panda",
  "Dreamy-Deer",
  "Lively-Lion",
  "Busy-Bee",
  "Fuzzy-Fox",
  "Jolly-Koala",
  "Witty-Wolf",
  "Sleepy-Sloth",
  "Cute-Kitten",
  "Silly-Squirrel",
  "Happy-Hare",
  "Cheery-Chimpanzee",
  "Mischievous-Monkey",
  "Lively-Tiger",
  "Bouncy-Dog",
  "Snazzy-Skunk",
  "Grinning-Gorilla",
  "Playful-Pig",
  "Jolly-Orangutan",
  "Fluffy-Bunny",
  "Lazy-Leopard",
  "Chirpy-Chipmunk",
  "Playful-Puppy",
  "Cuddly-Cub",
  "Snuggly-Panda",
  "Dreamy-Deer",
  "Lively-Lion",
  "Busy-Bee",
  "Fuzzy-Fox",
  "Jolly-Koala",
  "Witty-Wolf"
];

function chooseRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateRandomName() {
  return `${chooseRandom(names)}-${Math.floor(10000 + Math.random() * 10000)}`;
}

export async function fetchRandomDefaultAvatarId() {
  return new URL(defaultAvatar, location.href).href;
}
